# Generated by Django 5.0.3 on 2024-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_actor_movie_director_movie_genres_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='main_picture',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='main_picture',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_picture',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
